### ISSUE TITLE
Optional feature for RubberduckWeb - use URL to parse VBA

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/RubberduckWeb#14]
Can optionally select an URL with VBA code into the web parser
But also the URL can be a valid GitHub or gitcode base either a bas/cls to check

**Comment by ckuhn203** [comment]
Can you clarify a bit how you'd like this to behave?

**Comment by PeterMTaylor** [comment]
Sure. I'll have a go explaining it this way... I was inspiried by this idea when about to give @Hosch250 my test file thinking about the rubberduckweb.

**Story:** Optionally allow the user specify which URL to parse using RubberduckWeb
_As a_ user of browsing the RubberduckWeb parser, _I want to_ explore several VBA code snippets shown using several URL's _so that_ I could evaluate which VBA code snippet parses/works better by RubberduckWeb (for whatever reason, testing or confirming details)

**Scenario 1:** URL source is a webpage
_Given that_ a user of RubberduckWeb provided a URL when asked
_And_ the source of the URL is detected as webpage
_When_ prompted by RubberduckWeb what is the URL to parse
_Then_ Rubberduck confirms to the user is this the correct VBA to parse 

Example: http://www.cpearson.com/Excel/Implements.aspx and wanted RubberduckWeb to process the Sorted VBA Program mentioned. RubberduckWeb may not permit user giving URL with multple VBA code in a single source. Thus the user may be asked to provide a txt file only for this purpose.

**Scenario 2**: URL source is a Github gist snippet
_Given that_ a user of RubberduckWeb provided a URL when asked
_And_ the source of the URL is detected as Github Gist file
_When_ prompted by RubberduckWeb what is the URL to parse
_Then_ Rubberduck confirms to the user Github Gist file is ready to parse

Example: https://gist.github.com/brucemcpherson/3403537 and want to see how the parses

**Scenario 3**: URL source is a Github file in the repository
_Given that_ a user of RubberduckWeb provided a URL when asked
_And_ the source of the URL is detected as Github file from the repository
_When_ prompted by RubberduckWeb what is the URL to parse
_Then_ Rubberduck confirms to the user Github VBA file is ready to parse

Example:  emptycDataSet/libraries/cDataRow.cls OR https://github.com/brucemcpherson/emptycDataSet/blob/master/libraries/cDataRow.cls and see how this file parses.

**Comment by retailcoder** [comment]
Seems like something that could get very complicated, very fast.

**Comment by ckuhn203** [comment]
Beyond how complicated it would be to figure out what is text and what is code on *arbitrary* websites and translating HTML to valid VBA code, this would open up the site to XSS attacks. I'm sorry. This one just isn't going to happen. It's a security risk for our users. I don't feel it's an undue burden to copy paste some code into the browser.

**Comment by Hosch250** [comment]
Also, putting code in URL's would be a GET call, and GET can't send nearly as much data as POST calls, like we use when you manually enter code in the website.

**Comment by PeterMTaylor** [comment]
Fair enough folks. At least this option is explored and views are presented and recorded therein.

**Comment by ckuhn203** [comment]
@PeterMTaylor, please don't think we're trying to be rude. It's just that... Well, our "job" is often very much about saying no to features that sound like a good idea, but don't fit with the overall goals and architecture of the project. It sucks, but it's also the reality and responsibility we have. 

As my cohorts cringe because I've not made a commit in nearly a year...

**Comment by retailcoder** [comment]
@ckuhn203 well... this very repository wouldn't exist without your contributions, as sporadic as they might be!

**Comment by PeterMTaylor** [comment]
@ckuhn203 not upset at all. It's a learning curve for me to reignite my IT skills as I hadn't used it for a long time and things have changed a lot. I'm looking for a different way by helping out. I more or less expect my ideas a bit on the wild side however appreciated the positive feedback along the way that I do receive so I know I can improve this art of programming in some way, especially knowing what goals and architect are.
