### ISSUE TITLE
Disable Project & Module naming inspections

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/RubberduckWeb#18]
The web inspections is triggering a few informational inspections that should probably be disabled for web, because we're the ones providing the VBProject and Module. I've not looked at the web implementation, but I'm assuming it's a matter of configuration.

![image](https://cloud.githubusercontent.com/assets/2716800/21110779/a3141bfe-c06c-11e6-923e-e09a50340ac5.png)

**Comment by retailcoder** [comment]
We'd have to cherry-pick inspection results' `Target.DeclarationType` and filter out `DeclarationType.Project` and `DeclarationType.ProceduralModule` to get these ones out of the way without outright disabling that inspection.

**Comment by ckuhn203** [comment]
Ahh. Not as simple as I thought. Cloning now.

**Comment by EBrown8534** [comment]
The results are currently of type `ICodeInspectionResult`, how trivial would it be to get the `Target.DeclarationType` from that?

**Comment by ckuhn203** [comment]
Dirty hack incoming @EBrown8534, just a sec.

**Comment by EBrown8534** [comment]
@ckuhn203 Alright, but I just fixed it, committing to my fork then adding PR...;)

**Comment by ckuhn203** [comment]
Oops. Just submitted #20 @EBrown8534...

**Comment by retailcoder** [comment]
...let's see which dirty hack is the cleanest :racehorse:

**Comment by EBrown8534** [comment]
@ckuhn203 It's all good, if you don't mind merge the PR you made and I'll move that code to the view to line up better with MVC's style, I also fixed another issue in my fix (which I haven't PR'd yet) which is "No issues were found" should display when no inspection results are returned.

Likewise, are we sure we don't want to use the method @retailcoder suggested? It's quite trivial:

            var results = Model.Where(o => ((InspectionResultBase)o).Target != null && ((InspectionResultBase)o).Target.DeclarationType != Rubberduck.Parsing.Symbols.DeclarationType.Project && ((InspectionResultBase)o).Target.DeclarationType != Rubberduck.Parsing.Symbols.DeclarationType.ProceduralModule);
            if (results.Count() > 0)
            {
                foreach (var item in results
                                        .OrderBy(o => o.QualifiedSelection.Selection.StartLine)
                                        .ThenBy(t => t.QualifiedSelection.Selection.StartColumn))
                {
                <tr>
                    <td width="50"><img alt="@item.Inspection.Severity" src="@severityIconUrls[item.Inspection.Severity]" /></td>
                    <td>@item.Description</td>
                    <td>@item.Inspection.Meta</td>
                    <td>@string.Format("L{0}C{1}", item.QualifiedSelection.Selection.StartLine, item.QualifiedSelection.Selection.StartColumn)</td>
                </tr>
                }
            <tr><td colspan="4">Note: Inspection results may differ when Rubberduck is running in the Visual Basic Editor (VBE) IDE, where referenced type libraries (VBA Standard library, Excel object model, etc.) are used by the resolver. Soon we'll serialize the declarations we're extracting from the most commonly used type libraries, to improve this online experience (experiment?). Some inspections are also explicitly excluded.</td></tr>
            }
            else
            {
                <tr><th colspan="4" class="text-center">No issues were found</th></tr>
            }

That fixed *both* issues at the same time.

**Comment by retailcoder** [comment]
@EBrown8534 that might remove inspection results where `Target` is `null` though; I like @ckuhn203's solution, which hardwires the actual inspection type. After all, we *are* looking at one specific inspection.

**Comment by comintern** [comment]
Are the inspections running with the default settings?  Wouldn't it be easier to just set the severity to "Ignore"?

**Comment by retailcoder** [comment]
@comintern they are. But that would disable the inspection altogether, not just filter out the specific results about the test module / test method names.

**Comment by ckuhn203** [comment]
@comintern that would disable all of the `UseMeaningfulName` inspections, so we would miss bad variable names.
