### ISSUE TITLE
Code Inspections need a "busy" indicator

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/RubberduckWeb#22]
A *lot* is going on upon clicking that [inspect] button. While it often happens very fast, or *reasonably* fast, sometimes (especially the initial run, or if a lot of code is involved, or if lots of inspection results get spawned) it can take quite a while.

Let's add a "busy" indicator to indicate we're working on it.

**Comment by EBrown8534** [comment]
This will be fixed in the next PR.
