### ISSUE TITLE
Expose the version of the referenced build via HTTP GET

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/RubberduckWeb#27]
Now that RDWEB references an actual RD build, we could use that to implement a version check in Rubberduck.

Let's expose a controller method that returns a string representing the RD build version that's running on the website; Rubberduck could then send a HTTP GET request and compare its build version against it, and know whether to prompt the user to upgrade.

Of course this means pushing an unreleased build on the website becomes a no-no.

Would be nice to have a dedicated controller for this, e.g. `http://rubberduckvba.com/build/version`.

**Comment by EBrown8534** [comment]
/Build/Version/Stable
    /Build/Version/Experimental

**Comment by retailcoder** [comment]
@EBrown8534 there's only one Rubberduck.dll assembly referenced though... I was thinking of simply exposing what we're currently showing above the *try it!* inspections box

**Comment by EBrown8534** [comment]
We can do `/Build/Version`, but I'd prefer to at least use `/Stable` especially if the goal is to do update  checking.

**Comment by EBrown8534** [comment]
The question is: how should we deal with all the RD libraries being potentially different versions? Should we, instead of `/Stable` use `/Rubberduck.dll`, `/Rubberduck.Parsing.dll`, et. al.?

**Comment by retailcoder** [comment]
@Ebrown8534 the version that RD displays in the splash form at startup is the build of the Rubberduck.dll library; the other libraries are just dependencies, basically.
