### ISSUE TITLE
Pictures are too wide

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/RubberduckWeb#3]
Pictures aren't scaling to the page size, and on a phone they bleed off the features and about page, which then lets user scroll to the right, ...which reveals another problem: the top bar (black area) doesn't fit the whole page width.

A patch-fix could be to make the pictures smaller to better fit the pages.

The real fix would be to do whatever it takes for the width of the top bar to _dictate_ the maximum width of the page, _everywhere_ on the page - even if it means scaling pictures down to fit.

**Comment by ckuhn203** [comment]
Should be a simple fix. I think all we need to do is add `.img-responsive` class to the image elements. 

 http://getbootstrap.com/css/

**Comment by retailcoder** [comment]
This doesn't appear to be a problem anymore.
