### ISSUE TITLE
Example code for each Inspection

### ISSUE THREAD

**Issue by EBrown8534** [rubberduck-vba/RubberduckWeb#32]
I was thinking last night in the middle of the night that we should have example code blocks that would trigger each inspection on the detail page of the inspection.

We already have a template and style for a "mock VBE debugger" that we could use to make it look/feel like VBA code.

I.e.: for `Option Explicit Inspection`:

    Public Sub Test()
    End Sub

Would highlight line 1.

**Comment by retailcoder** [comment]
I don't know about the highlighting, but I was thinking to add two resource strings per inspection the other day (looking at the generated "details" pages). One would be a snippet that triggers the inspection, the other would be a similar snippet that doesn't trigger it.

For example, this would trigger `UnassignedVariableUsage`:

    Private Sub DoSomething()
        Dim foo As Long
        Debug.Print foo
    End Sub

And this similar snippet wouldn't:

    Private Sub DoSomething()
        Dim foo As Long
        foo = 42
        Debug.Print foo
    End Sub

**Comment by retailcoder** [comment]
This is now live! 🎉
