### ISSUE TITLE
404 on a phone

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/RubberduckWeb#33]
Chrome on Android 
![tmp_21815-screenshot_20161228-221516-1634295208](https://cloud.githubusercontent.com/assets/16574009/21520808/8d922abe-cd4b-11e6-8e90-d2ab1178b2e0.png)

![tmp_21815-screenshot_20161228-221611-146596917](https://cloud.githubusercontent.com/assets/16574009/21520813/9a214a12-cd4b-11e6-9594-14f2ee6d1011.png)

**Comment by EBrown8534** [comment]
*Unfortunately* that's controlled by bootstrap. The modal popup is out of my control.

The best I can do is scale it for HDPI screens. I'll look into this tonight.

**Comment by EBrown8534** [comment]
For HDPI screens I took most of the static width assignments out, centered the buttons, and made it span the whole screen. I'll try to get a screenshot up later (probably in the morning).
