### ISSUE TITLE
Remote repository login failed

### ISSUE THREAD

**Issue by Fl0x23** [rubberduck-vba/RubberduckWeb#43]
When I start excel and I try to connect with the remote repository (Login) than excel is terminated every time.
![grafik](https://user-images.githubusercontent.com/20031926/30331127-3bf792aa-97d7-11e7-840e-f9bc03b3b5ff.png)

**Comment by retailcoder** [comment]
Hi,

Not sure which version you're using, but [this is definitely a known issue](https://github.com/rubberduck-vba/Rubberduck/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-source-control). The integrated Source Control panel has been disabled by default in the later releases, it is now dubbed an "experimental feature" and needs to be explicitly enabled through Rubberduck settings.

The entire Source Control functionality is undergoing a complete overhaul. In the meantime, the latest [v2.1 pre-release] build includes "export project" functionality which lets you specify a folder to export all modules in a project at once, from a right-click in the *Code Explorer* toolwindow; from there you can use your favorite git client to manage remotes.

BTW you're in the wrong repository, this is the project's website.
