### ISSUE TITLE
RD Web Inspector fails to Parse 'Implements IClass'

### ISSUE THREAD

**Issue by AlexC84** [rubberduck-vba/RubberduckWeb#47]
If I inspect the following single line of code using the RD web inspector:
`Implements IClass`

I get the following error returned:

> Rubberduck failed to parse your code. Please check the input and try again.

If I comment out the Implements statement:
`'Implements IClass`

then the code is successfully parsed and warns me about a missing 'Option Explicit' as expected

**Comment by retailcoder** [comment]
Updated the website with a 2.2 (pre-release) build - could not get the inspection settings loaded... update site no longer features online inspector. Closing this issue for now.
