### ISSUE TITLE
Cannot get source control to work

### ISSUE THREAD

**Issue by CKlijs** [rubberduck-vba/RubberduckWeb#48]
After activating source control in the settings. I cannot get it to work properly. I made a local repository, no changes appear in the changes list.
See the error log included with this issue
[RubberduckLog.txt](https://github.com/rubberduck-vba/RubberduckWeb/files/1426163/RubberduckLog.txt)

**Comment by Hosch250** [comment]
Please post this on the main repo: https://github.com/rubberduck-vba/Rubberduck
