### ISSUE TITLE
The web indenter does not understand one line if statements

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/RubberduckWeb#49]
MCVE:

```vba
Private Sub MCVE()
If Foo Then
Whatever
Else 
If Bar Then Something
EndIf
End Sub
```

gets indented to

```vba
Private Sub MCVE()
    If Foo Then
        Whatever
    Else
        If Bar Then Something
        EndIf
    End Sub
```

instead of 

```vba
Private Sub MCVE()
    If Foo Then
        Whatever
    Else
        If Bar Then Something
    EndIf
End Sub
```

Doing the same in Rubberduck inside Excel produces the correct result.

**Comment by retailcoder** [comment]
Given it's the exact same code performing the indentation... this looks like a very tricky thing to fix.

**Comment by retailcoder** [comment]
That would be the regex here:

https://github.com/rubberduck-vba/Rubberduck/blob/dea7220302fc660d328e2b77b8a8a9df048a46a3/Rubberduck.SmartIndenter/AbsoluteCodeLine.cs#L21
