### ISSUE TITLE
"Rubberduck this"

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/RubberduckWeb#5]
Let's reference the latest Rubberduck build (or should it be the latest *release* build?), and add a "Rubberduck this" page, where the user can paste some VBA code in a fancypants textbox with prettified code, and we grab that, mock up a VBE environment exactly like we do in the `Rubberduck.Tests` project (we'll have to duplicate the mocking code, or reference the test project too), and then run code inspections on it.

Needs a "parser state" check, too.

**Comment by ckuhn203** [comment]
I was actually thinking about this last night. I'm unsure if we should use the last release, or the current build. I couldn't make up my mind.
