### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/RubberduckWeb#50]
As @Vogel612 mentioned over in [Rubberduck-VBA](https://github.com/rubberduck-vba/Rubberduck/issues/3754#issuecomment-363742928) this is probably a more fitting place to talk about making the site viable for HTTPS.

I've somewhat recently created an SSL certificate for my own domain via [Let's Encrypt](https://letsencrypt.org/getting-started/) and - as far as I'm concerned - it was a rather simple process. The details depend upon the domain provider's infrastructure, so I don't think it's useful for me to go too much into detail about that. But my provider (a large German provider) has support for Let's Encrypt certificates already implemented, so in my case it was as simple as entering some values into a web form.

I'm not quite sure what else to say here, other than that in my opinion Let's Encrypt is absolutely support-worthy - and be it only by spreading the adoption of HTTPS. :)

Does anyone have opinions about Let's Encrypt? Easier/Better alternatives? Objections?

**Comment by Inarion** [comment]
I've just come across [this article describing some state-level shenanigans with insecure download sites](https://citizenlab.ca/2018/03/bad-traffic-sandvines-packetlogic-devices-deploy-government-spyware-turkey-syria/). While I'm well aware that a VBA add-in would likely never be popular enough to become a target for such actions, I still think that one should at least try to make the internet more secure. As such I felt it was a fitting occasion for a small bump in here. :)

**Comment by Inarion** [comment]
I'll leave a short summary from chat regarding this topic:  
It appears the current domain host (GoDaddy) does not support LetsEncrypt and likely won't in the future. The current contract with GoDaddy expires early 2019. @retailcoder 's plan is to not renew the contract and then transfer the domain to a different host (Azure?) that seems to be better in about all aspects. Once the new host is in place, it should be trivial to then set up LetsEncrypt / https.

**Comment by Zomis** [comment]
I started using Let's Encrypt for my site(s) last year and I also recommend Let's Encrypt.

**Comment by retailcoder** [comment]
Completed (still GoDaddy but eh)
