### ISSUE TITLE
Does Rubberduck have a Source Control feature?

### ISSUE THREAD

**Issue by bsacheri** [rubberduck-vba/RubberduckWeb#54]
Google shows a link to this page but the page has errors.  
[rubberduckvba.com/SourceControl](url)

The cached version of this page is:
[http://webcache.googleusercontent.com/search?q=cache:oLO0Ksa1AkcJ:rubberduckvba.com/SourceControl+&cd=1&hl=en&ct=clnk&gl=us](http://webcache.googleusercontent.com/search?q=cache:oLO0Ksa1AkcJ:rubberduckvba.com/SourceControl+&cd=1&hl=en&ct=clnk&gl=us)

It's not clear to me if source control is a feature of the product for end users, or only showing how Rubberduck itself is maintained.

**Comment by IvenBach** [comment]
RD did have source control feature. https://github.com/rubberduck-vba/Rubberduck/pull/3782 It was decided to remove in favor of maintaining, because of limited resources, as it had been somewhat troublesome feature.
