### ISSUE TITLE
Parser Error reported on certain For Next loop structure

### ISSUE THREAD

**Issue by chrisneilsen** [rubberduck-vba/RubberduckWeb#55]
Write a nested `For Next` in the form

    For x = a To b
    For y = c To d
        ' ...
    Next y, x

throws a Parser Error on the `Next y, x`

> extraneous input ',' expecting {<EOF>, ':', REM, NEWLINE, ''', WS, LINE_CONTINUATION}

**Comment by retailcoder** [comment]
Thanks for reporting this, I never knew this was legal! Mind opening this issue on the [main Rubberduck repository](https://github.com/rubberduck-vba/Rubberduck/issues/new) though?
