### ISSUE TITLE
Install wordpress to new subdomain blog.rubberduckvba.com

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/RubberduckWeb#6]
Let's migrate away from wordpress.com and use our own domain for the blog.

**Comment by EBrown8534** [comment]
Do we want to self-author this in the current website (`/Blog`) or use a separate piece of software for it?

**Comment by ckuhn203** [comment]
It was a *long* time ago, but was thinking of just migrating the wordpress.com blog to a self hosted Wordpress site at blog.rubberduckvba.com. Honestly, probably not ever going to be a big deal.
