### ISSUE TITLE
Website still mentions Source Control

### ISSUE THREAD

**Issue by GadgetSteve** [rubberduck-vba/RubberduckWeb#63]
The headline of the web page reads "From unit testing to **source control**, from code inspections to refactorings, programming in VBA will never be the same."

However, #3758 triggered the removal of source control (git) from the project - the recommendation is to use the Export feature and then version control the resulting file(s) or structure. Maybe changing the phrase above to read something like:
"From unit testing to code export *(allowing source control with your preferred tools)*, from code inspections to refactorings, programming in VBA will never be the same."

**Comment by retailcoder** [comment]
Hey @GadgetSteve, thanks for reporting this - you're right: the website is terribly outdated, it desperately needs a refresher! I've transferred this issue over to the website's own repository, so it can be tracked and closed when a commit fixes it. Cheers!
