### ISSUE TITLE
Inspections list doesn’t render well on mobile

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck-vba/RubberduckWeb#75]
The current inspections list view renders as a table with two columns. When viewing on mobile, only the first of the two table columns is visible. 

I would recommend rendering the list as a `<ul/>` and using CSS `columns` to automatically render the number of columns that will fit on screen. 

https://developer.mozilla.org/en-US/docs/Web/CSS/columns

**Comment by retailcoder** [comment]
Looks pretty neat now (albeit not mobile-specific), with pagination and collapsible panels. Best viewed in landscape :)
