### ISSUE TITLE
Link to original Smart Indenter page is dead

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/RubberduckWeb#76]
Should we replace the dead link with a [Wayback Machine](https://web.archive.org/web/20180806191001fw_/http://www.oaltd.co.uk/Indenter/Default.htm) link to the original page, or just rework that paragraph?

**Comment by Vogel612** [comment]
I personally would prefer linking to wayback, if only to simplify attribution (because the previous work we built on was quite extensive).

**Comment by retailcoder** [comment]
done
