### ISSUE TITLE
Add annotations list to main site

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/RubberduckWeb#77]
https://rubberduckvba.wordpress.com/2019/12/14/rubberduck-annotations/ and https://github.com/rubberduck-vba/Rubberduck/wiki/VB_Attribute-Annotations contain information for the annotations but nothing is found on the main site. If http://rubberduckvba.com/Annotations was added to the site as one of the links at the top it would increase discoverability.

**Comment by MDoerner** [comment]
Related to https://github.com/rubberduck-vba/Rubberduck/issues/5380

**Comment by retailcoder** [comment]
Current content was loaded from the Rubberduck.Parsing.xml asset off the CI build for the WIP PR that will start publishing this xmldoc data.

Since the content is up, I'm closing this issue - the related pending work is on the RD repo.
